services:
  tektune:
    container_name: tektune
    build:
      context: https://github.com/BuggyPasta/TekTune.git
    ports:
      - "3600:3600"
    volumes:
      - /home/alex/docker_backup/tektune:/data/tektune
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped 